export const dummyBonusAndChallengeData = [
    {
        id: '01',
        name: 'Candice',
        description: 'cand...............',
        startDate: '08/09/2024',
        endDate: '08/10/2024',
        requiredNumber: 2,
        bonusAmount: 200,
        role: 'Client',
    },
    {
        id: '02',
        name: 'Candice',
        description: 'cand...............',
        startDate: '08/09/2024',
        endDate: '08/10/2024',
        requiredNumber: 2,
        bonusAmount: 200,
        role: 'Client',
    },
    {
        id: '03',
        name: 'Candice',
        description: 'cand...............',
        startDate: '08/09/2024',
        endDate: '08/10/2024',
        requiredNumber: 2,
        bonusAmount: 200,
        role: 'Client',
    },
    {
        id: '04',
        name: 'Candice',
        description: 'cand...............',
        startDate: '08/09/2024',
        endDate: '08/10/2024',
        requiredNumber: 2,
        bonusAmount: 200,
        role: 'Client',
    },
    {
        id: '05',
        name: 'Candice',
        description: 'cand...............',
        startDate: '08/09/2024',
        endDate: '08/10/2024',
        requiredNumber: 2,
        bonusAmount: 200,
        role: 'Client',
    },
    {
        id: '06',
        name: 'Candice',
        description: 'cand...............',
        startDate: '08/09/2024',
        endDate: '08/10/2024',
        requiredNumber: 2,
        bonusAmount: 200,
        role: 'Client',
    },
];
