export const dummyBookingData = [
    {
        id: '01',
        client: {
            name: 'Candice',
            email: 'candice@gmail.com',
            image: 'https://img.freepik.com/premium-vector/person-with-blue-shirt-that-says-name-person_1029948-7040.jpg?semt=ais_hybrid&w=740',
        },
        provider: {
            name: 'Candice',
            email: 'candice@gmail.com',
            image: 'https://img.freepik.com/premium-vector/person-with-blue-shirt-that-says-name-person_1029948-7040.jpg?semt=ais_hybrid&w=740',
        },
        serviceLocation: '4517 Washington Ave. Manchester',
        price: 130,
        category: 'Hair',
        apptTime: '2/11/12;02:00PM',
    },
    {
        id: '02',
        client: {
            name: 'Candice',
            email: 'candice@gmail.com',
            image: 'https://img.freepik.com/premium-vector/person-with-blue-shirt-that-says-name-person_1029948-7040.jpg?semt=ais_hybrid&w=740',
        },
        provider: {
            name: 'Candice',
            email: 'candice@gmail.com',
            image: 'https://img.freepik.com/premium-vector/person-with-blue-shirt-that-says-name-person_1029948-7040.jpg?semt=ais_hybrid&w=740',
        },
        serviceLocation: '4517 Washington Ave. Manchester',
        price: 130,
        category: 'Hair',
        apptTime: '2/11/12;02:00PM',
    },
    {
        id: '03',
        client: {
            name: 'Candice',
            email: 'candice@gmail.com',
            image: 'https://img.freepik.com/premium-vector/person-with-blue-shirt-that-says-name-person_1029948-7040.jpg?semt=ais_hybrid&w=740',
        },
        provider: {
            name: 'Candice',
            email: 'candice@gmail.com',
            image: 'https://img.freepik.com/premium-vector/person-with-blue-shirt-that-says-name-person_1029948-7040.jpg?semt=ais_hybrid&w=740',
        },
        serviceLocation: '4517 Washington Ave. Manchester',
        price: 130,
        category: 'Hair',
        apptTime: '2/11/12;02:00PM',
    },
    {
        id: '04',
        client: {
            name: 'Candice',
            email: 'candice@gmail.com',
            image: 'https://img.freepik.com/premium-vector/person-with-blue-shirt-that-says-name-person_1029948-7040.jpg?semt=ais_hybrid&w=740',
        },
        provider: {
            name: 'Candice',
            email: 'candice@gmail.com',
            image: 'https://img.freepik.com/premium-vector/person-with-blue-shirt-that-says-name-person_1029948-7040.jpg?semt=ais_hybrid&w=740',
        },
        serviceLocation: '4517 Washington Ave. Manchester',
        price: 130,
        category: 'Hair',
        apptTime: '2/11/12;02:00PM',
    },
    {
        id: '05',
        client: {
            name: 'Candice',
            email: 'candice@gmail.com',
            image: 'https://img.freepik.com/premium-vector/person-with-blue-shirt-that-says-name-person_1029948-7040.jpg?semt=ais_hybrid&w=740',
        },
        provider: {
            name: 'Candice',
            email: 'candice@gmail.com',
            image: 'https://img.freepik.com/premium-vector/person-with-blue-shirt-that-says-name-person_1029948-7040.jpg?semt=ais_hybrid&w=740',
        },
        serviceLocation: '4517 Washington Ave. Manchester',
        price: 130,
        category: 'Hair',
        apptTime: '2/11/12;02:00PM',
    },
    {
        id: '06',
        client: {
            name: 'Candice',
            email: 'candice@gmail.com',
            image: 'https://img.freepik.com/premium-vector/person-with-blue-shirt-that-says-name-person_1029948-7040.jpg?semt=ais_hybrid&w=740',
        },
        provider: {
            name: 'Candice',
            email: 'candice@gmail.com',
            image: 'https://img.freepik.com/premium-vector/person-with-blue-shirt-that-says-name-person_1029948-7040.jpg?semt=ais_hybrid&w=740',
        },
        serviceLocation: '4517 Washington Ave. Manchester',
        price: 130,
        category: 'Hair',
        apptTime: '2/11/12;02:00PM',
    },
    {
        id: '07',
        client: {
            name: 'Candice',
            email: 'candice@gmail.com',
            image: 'https://img.freepik.com/premium-vector/person-with-blue-shirt-that-says-name-person_1029948-7040.jpg?semt=ais_hybrid&w=740',
        },
        provider: {
            name: 'Candice',
            email: 'candice@gmail.com',
            image: 'https://img.freepik.com/premium-vector/person-with-blue-shirt-that-says-name-person_1029948-7040.jpg?semt=ais_hybrid&w=740',
        },
        serviceLocation: '4517 Washington Ave. Manchester',
        price: 130,
        category: 'Hair',
        apptTime: '2/11/12;02:00PM',
    },
    {
        id: '08',
        client: {
            name: 'Candice',
            email: 'candice@gmail.com',
            image: 'https://img.freepik.com/premium-vector/person-with-blue-shirt-that-says-name-person_1029948-7040.jpg?semt=ais_hybrid&w=740',
        },
        provider: {
            name: 'Candice',
            email: 'candice@gmail.com',
            image: 'https://img.freepik.com/premium-vector/person-with-blue-shirt-that-says-name-person_1029948-7040.jpg?semt=ais_hybrid&w=740',
        },
        serviceLocation: '4517 Washington Ave. Manchester',
        price: 130,
        category: 'Hair',
        apptTime: '2/11/12;02:00PM',
    },
    {
        id: '09',
        client: {
            name: 'Candice',
            email: 'candice@gmail.com',
            image: 'https://img.freepik.com/premium-vector/person-with-blue-shirt-that-says-name-person_1029948-7040.jpg?semt=ais_hybrid&w=740',
        },
        provider: {
            name: 'Candice',
            email: 'candice@gmail.com',
            image: 'https://img.freepik.com/premium-vector/person-with-blue-shirt-that-says-name-person_1029948-7040.jpg?semt=ais_hybrid&w=740',
        },
        serviceLocation: '4517 Washington Ave. Manchester',
        price: 130,
        category: 'Hair',
        apptTime: '2/11/12;02:00PM',
    },
    {
        id: '10',
        client: {
            name: 'Candice',
            email: 'candice@gmail.com',
            image: 'https://img.freepik.com/premium-vector/person-with-blue-shirt-that-says-name-person_1029948-7040.jpg?semt=ais_hybrid&w=740',
        },
        provider: {
            name: 'Candice',
            email: 'candice@gmail.com',
            image: 'https://img.freepik.com/premium-vector/person-with-blue-shirt-that-says-name-person_1029948-7040.jpg?semt=ais_hybrid&w=740',
        },
        serviceLocation: '4517 Washington Ave. Manchester',
        price: 130,
        category: 'Hair',
        apptTime: '2/11/12;02:00PM',
    },
    {
        id: '11',
        client: {
            name: 'Candice',
            email: 'candice@gmail.com',
            image: 'https://img.freepik.com/premium-vector/person-with-blue-shirt-that-says-name-person_1029948-7040.jpg?semt=ais_hybrid&w=740',
        },
        provider: {
            name: 'Candice',
            email: 'candice@gmail.com',
            image: 'https://img.freepik.com/premium-vector/person-with-blue-shirt-that-says-name-person_1029948-7040.jpg?semt=ais_hybrid&w=740',
        },
        serviceLocation: '4517 Washington Ave. Manchester',
        price: 130,
        category: 'Hair',
        apptTime: '2/11/12;02:00PM',
    },
];
